change: Status now has an instance in it instead of a reference
There is an issue of rust: a fake modify-a-borrowed problem:

```rust
struct Inst { a: i32, }
struct St<'a> { inst: &'a Inst, }
fn borrow_it(s: &mut St) { }

fn main() {
    let mut i = Inst{a:3};
    let mut s = St{ inst: &i, };
    i.a = 5;
    borrow_it(&mut s);
}
```

```
error[E0506]: cannot assign to `i.a` because it is borrowed
  --> refmut.rs:16:5
   |
14 |         inst: &i,
   |               -- borrow of `i.a` occurs here
15 |     };
16 |     i.a = 5;
   |     ^^^^^^^ assignment to borrowed `i.a` occurs here
17 |     borrow_it(&mut s);
   |               ------ borrow later used here

error: aborting due to previous error
```